apiVersion: apps/v1
kind: Deployment
metadata:
  name: pumpwood-auth-static
spec:
  replicas: 1
  selector:
    matchLabels:
      type: static
      endpoint: pumpwood-auth-app
      function: auth
  template:
    metadata:
      labels:
        type: static
        endpoint: pumpwood-auth-app
        function: auth
    spec:
      imagePullSecrets:
        - name: dockercfg
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: function
                operator: NotIn
                values:
                - system
      containers:
      - name: pumpwood-auth-static
        image: {repository}pumpwood-auth-static:{version}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "10m"
        ports:
        - containerPort: 5000
---
apiVersion : "v1"
kind: Service
metadata:
  name: pumpwood-auth-admin-static
  labels:
    type: static
    endpoint: pumpwood-auth-app
    function: auth
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    type: static
    endpoint: pumpwood-auth-app
    function: auth
