apiVersion: apps/v1
kind: Deployment
metadata:
  name: pumpwood-auth-app
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      type: app
      endpoint: pumpwood-auth-app
      function: auth
  template:
    metadata:
      labels:
        type: app
        endpoint: pumpwood-auth-app
        function: auth
    spec:
      imagePullSecrets:
        - name: dockercfg
      volumes:
      - name: secrets
        secret:
          secretName: pumpwood-auth
      volumes:
      - name: gcp--storage-key
        secret:
          secretName: gcp--storage-key
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: function
                operator: NotIn
                values:
                - system
      containers:
      - name: pumpwood-auth-app
        image: {repository}pumpwood-auth-app:{version}
        resources:
          requests:
            memory: "{requests_memory}"
            cpu:  "{requests_cpu}"
          limits:
            memory: "{limits_memory}"
            cpu:  "{limits_cpu}"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: gcp--storage-key
            readOnly: true
            mountPath: /etc/secrets
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health-check/pumpwood-auth-app/
            port: 5000
        env:
        - name: DEBUG
          value: "{debug}"

        - name: WORKERS_TIMEOUT
          value: "{workers_timeout}"
        - name: N_WORKERS
          value: "{n_workers}"
        - name: PUMPWOOD_AUTH_IS_RABBITMQ_LOG
          value: "{rabbitmq_log}"

        # HASH_SALT
        - name: HASH_SALT
          valueFrom:
            secretKeyRef:
              name: hash-salt
              key: hash_salt

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: pumpwood-auth
              key: secret_key

        # Database
        - name: DB_USERNAME
          value: {db_username}
        - name: DB_HOST
          value: {db_host}
        - name: DB_PORT
          value: "{db_port}"
        - name: DB_DATABASE
          value: {db_database}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pumpwood-auth
              key: db_password

        # RabbitMQ
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-main-secrets
              key: password

        # Microservice
        - name: MICROSERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pumpwood-auth
              key: microservice_password

        # Email
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: pumpwood-auth
              key: email_host_user
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pumpwood-auth
              key: email_host_password

        ###########
        # STORAGE #
        - name: STORAGE_BUCKET_NAME
          value: {bucket_name}
        - name: STORAGE_TYPE
          valueFrom:
            configMapKeyRef:
              name: storage
              key: storage_type

        # GCP
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/key-storage.json"

        # AZURE
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure--storage-key
              key: azure_storage_connection_string

        # AWS
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws--storage-key
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws--storage-key
              key: aws_secret_access_key

        ############
        # Metabase #
        - name: METABASE_SITE_URL
          valueFrom:
            configMapKeyRef:
              name: metabase
              key: site_url
        - name: METABASE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: metabase
              key: embedding_secret_key

        #######
        # MFA #
        - name: PUMPWOOD__MFA__APPLICATION_NAME
          value: {mfa_application_name}
        - name: PUMPWOOD__MFA__TOKEN_EXPIRATION_INTERVAL
          value: {mfa_token_expiration_interval}
        - name: PUMPWOOD__MFA__TWILIO_SENDER_PHONE_NUMBER
          value: {mfa_twilio_sender_phone_number}
        - name: PUMPWOOD__MFA__TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: metabase
              key: mfa_twilio_account_sid
        - name: PUMPWOOD__MFA__TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: metabase
              key: mfa_twilio_auth_token
---
apiVersion : "v1"
kind: Service
metadata:
  name: pumpwood-auth-app
  labels:
    type: app
    endpoint: pumpwood-auth-app
    function: auth
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    type: app
    endpoint: pumpwood-auth-app
    function: auth
