apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pumpwood-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
      endpoint: pumpwood-prediction-app
      function: prediction
  template:
    metadata:
      labels:
        type: db
        endpoint: pumpwood-prediction-app
        function: prediction
    spec:
      imagePullSecrets:
        - name: dockercfg
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory

      containers:
      # PGBouncer Container
      - name: pgbouncer
        image: bitnami/pgbouncer:1.21.0
        env:
        - name: POSTGRESQL_USERNAME
          value: pumpwood
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pumpwood-prediction
              key: db_password
        - name: POSTGRESQL_HOST
          value: 0.0.0.0
        - name: PGBOUNCER_DATABASE
          value: pumpwood
        - name: PGBOUNCER_SET_DATABASE_USER
          value: 'yes'
        - name: PGBOUNCER_SET_DATABASE_PASSWORD
          value: 'yes'
        - name: PGBOUNCER_POOL_MODE
          value: transaction
        ports:
        - containerPort: 6432

      - name: postgres
        image: {repository}/test-db-pumpwood-prediction:{version}
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_API
          value: http://load-balancer:8001/
        - name: SERVICE_URL
          value: http://postgres-pumpwood-prediction-no-bouncer:5000/
        resources:
          limits:
            memory: "1Gi"
            cpu:  "1000m"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        ports:
        - containerPort: 5432
---
apiVersion : "v1"
kind: Service
metadata:
  name: postgres-pumpwood-prediction
  labels:
    type: db
    endpoint: pumpwood-prediction-app
    function: prediction
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 6432
  selector:
    type: db
    endpoint: pumpwood-prediction-app
    function: prediction
---
apiVersion : "v1"
kind: Service
metadata:
  name: postgres-pumpwood-prediction-no-bouncer
  labels:
    type: db-no-bouncer
    endpoint: pumpwood-prediction-app
    function: prediction
spec:
  type: ClusterIP
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432
    - name: regen-port
      port: 5000
      targetPort: 5000
  selector:
    type: db
    endpoint: pumpwood-prediction-app
    function: prediction
