apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
      endpoint: hive-metastore
  template:
    metadata:
      labels:
        type: db
        endpoint: hive-metastore
    spec:
      imagePullSecrets:
        - name: dockercfg
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: function
                operator: NotIn
                values:
                - system
      containers:
      - name: postgres
        image: {repository}test-db-hive-metastore:{version}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "20Mi"
            cpu:  "1m"
          limits:
            memory: "{limits_memory}"
            cpu:  "{limits_cpu}"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        ports:
        - containerPort: 5432
---
apiVersion : "v1"
kind: Service
metadata:
  name: postgres-hive-metastore
  labels:
    type: db-no-bouncer
    endpoint: hive-metastore
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    type: db
    endpoint: hive-metastore
