apiVersion : "v1"
kind: Service
metadata:
  name: rabbitmq-main
  labels:
    type: queue
    queue: rabbitmq-main
spec:
  type: ClusterIP
  ports:
    - name: ui
      port: 15672
      targetPort: 15672
    - name: broker
      port: 5672
      targetPort: 5672
  selector:
    type: queue
    queue: rabbitmq-main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-main
spec:
  replicas: 1
  selector:
    matchLabels:
      type: queue
      queue: rabbitmq-main
  template:
    metadata:
      labels:
        type: queue
        queue: rabbitmq-main
    spec:
      restartPolicy: Always
      volumes:
      - name: secrets
        secret:
          secretName: rabbitmq-main-secrets
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: function
                operator: NotIn
                values:
                - system
      containers:
      - name: rabbitmq-main
        image: rabbitmq:3.8-management
        resources:
          requests:
            cpu: "1m"
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: 'pumpwood'
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-main-secrets
              key: password
        ports:
        - name: 'queue'
          containerPort: 5672
        - name: 'ui'
          containerPort: 15672
